// build.js — runs on Netlify at build time to generate firebase-config.js
// from environment variables set in the Netlify dashboard.
const fs = require('fs');

const config = {
  apiKey:            process.env.FIREBASE_API_KEY            || '',
  authDomain:        process.env.FIREBASE_AUTH_DOMAIN        || '',
  projectId:         process.env.FIREBASE_PROJECT_ID         || '',
  storageBucket:     process.env.FIREBASE_STORAGE_BUCKET     || '',
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || '',
  appId:             process.env.FIREBASE_APP_ID             || '',
  measurementId:     process.env.FIREBASE_MEASUREMENT_ID     || '',
};

const content = `// Auto-generated by build.js — DO NOT edit manually.
window.FIREBASE_CONFIG = ${JSON.stringify(config, null, 2)};
`;

fs.writeFileSync('firebase-config.js', content);
console.log('✅ firebase-config.js generated successfully.');
